### ISSUE TITLE
Getting 0 exit code when agent decryption fails

### ISSUE THREAD

**Issue by ghost** [leighmcculloch/sshagentsign#3]
Various error conditions are giving a 0 exit code. Examples:

```
$ echo a | sshcrypt agent-decrypt
Encrpted data is invalid format

$ echo $?
0
```

```
$ cat .encrypted_password | sshcrypt agent-decrypt
agent: failed to sign challenge

$ echo $?
0
```

Looking at the code it appears there are many 

```
if err != nil {
   fmt.Println(err)
   return
}
```

Instead of 
```
if err != nil {
 fail(err)
}
```

Is there are particular reason for this?

**Comment by leighmcculloch** [comment]
>Is there are particular reason for this?

I don't think so. I think this is likely a bug. Thanks for submitting a PR!
