### ISSUE TITLE
Use with ecdsa private keys

### ISSUE THREAD

**Issue by pellcorp** [leighmcculloch/sshagentsign#7]
This is not an issue for the sshcrypt encrypt and decrypt tools, just the ssh-agent ones.  But I can encrypt and decrypt just fine.

I can agent-encrypt but not decrypt, wondering if there is something I can be looking for to figure out why it does not work with termux.

**Comment by pellcorp** [comment]
I actually figured out what it was, I was using a id_ecdsa private key.  Soon as I replaced with a stock standard rsa key all worked fine.

**Comment by pellcorp** [comment]
I looked into this in a bit more detail, seems that the signature from an ecdsa key is not the same every time, so cannot use it as a symmetric key.

**Comment by leighmcculloch** [comment]
Interesting. Do you know why this is?

**Comment by jstasiak** [comment]
This seems relevant, I'm afraid it means using ECDSA with sshcrypt is not possible: https://github.com/Yubico/yubico-piv-tool/issues/190

**Comment by pellcorp** [comment]
I regenerated my key as RSA a long time ago!  It would be nice to add some validation / documentation around ECDSA keys and sshcrypt and then close this issue.

**Comment by leighmcculloch** [comment]
>It would be nice to add some validation / documentation around ECDSA keys and sshcrypt and then close this issue.

Contributions are welcome. I'll do my best to review a contribution, but have limited capacity so please keep the contribution hyper-focused and small.

Also please note this project is experimental as is stated in the README.

**Comment by pellcorp** [comment]
Fair comment, Im in the same situation with limited time.

**Comment by pellcorp** [comment]
Even a note in the readme, would have saved me several hours of stuffing around. hopefully might save someone else the same effort :-)

https://github.com/leighmcculloch/sshcrypt/pull/9

**Comment by leighmcculloch** [comment]
Ah, a note in the readme is easy, great idea! I love solutions that are not write more code 😄. Thanks @pellcorp!

**Comment by pellcorp** [comment]
no problems, all I know is that a note like this would have saved me time, and that is what I was trying to save others :-)

thanks again for your work

cheers
